"""test1

Revision ID: 05086d407e64
Revises: 9bc90cd0b9a6
Create Date: 2017-08-16 23:56:04.934419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05086d407e64'
down_revision = '9bc90cd0b9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_comment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_comment')
    # ### end Alembic commands ###
