"""add comment like

Revision ID: 9bc90cd0b9a6
Revises: 0efe29c29a46
Create Date: 2017-08-16 23:12:18.622381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc90cd0b9a6'
down_revision = '0efe29c29a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_comment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column(u'comments', sa.Column('likes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comments_likes'), 'comments', ['likes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_likes'), table_name='comments')
    op.drop_column(u'comments', 'likes')
    op.drop_table('like_comment')
    # ### end Alembic commands ###
