"""fix author

Revision ID: b9a8a1b63b4f
Revises: 10e61d45cc01
Create Date: 2017-08-07 22:10:35.853549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9a8a1b63b4f'
down_revision = '10e61d45cc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'comments_ibfk_1', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    op.drop_column('comments', 'auhor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('auhor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(u'comments_ibfk_1', 'comments', 'users', ['auhor_id'], ['id'])
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###
