"""add like post

Revision ID: f0785819f99a
Revises: 120804c3552d
Create Date: 2017-08-11 13:38:40.958731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0785819f99a'
down_revision = '120804c3552d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column(u'posts', sa.Column('likes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_likes'), 'posts', ['likes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_likes'), table_name='posts')
    op.drop_column(u'posts', 'likes')
    op.drop_table('like')
    # ### end Alembic commands ###
